name: Testing before deployment
on:
  pull_request:
    branches:
      - dev
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set Up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Set Up Android SDK
        uses: android-actions/setup-android@v3

      - name: Change Wrapper Permissions
        run: chmod +x ./gradlew

      - name: Create Google Services File
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run:
          echo $GOOGLE_SERVICES_JSON | base64 -di > ./app/google-services.json

      - name: Run Gradle Tests
        run: ./gradlew test